spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/yj-inventory-management
#    url: jdbc:mysql://localhost/inventory_management
    username: sa
#    username: root
    password:
    driver-class-name: org.h2.Driver
#    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
#    open-in-view: false


logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
